<a href="https://colab.research.google.com/github/DimiGretsistas/Automated-Customers-Reviews-Project/blob/main/notebooks/04_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Review Summarization

**Goals**
- Use a small generative model to create short recommendation articles from clustered product reviews.
- This notebook recreates the clustered sample directly, so it does not depend on the clustering notebook.

In [3]:
import pandas as pd

# load cleaned dataset from Colab
df = pd.read_csv(
    "/content/clean_reviews.csv",
    engine="python",
    on_bad_lines="skip"
)

# inspect data
df.head()

,name,reviews.rating,reviews.text,sentiment,clean_review
0,AmazonBasics AAA Performance Alkaline Batterie...,3,I order 3 of them and one of the item is bad q...,neutral,i order 3 of them and one of the item is bad q...
1,AmazonBasics AAA Performance Alkaline Batterie...,4,Bulk is always the less expensive way to go fo...,positive,bulk is always the less expensive way to go fo...
2,AmazonBasics AAA Performance Alkaline Batterie...,5,Well they are not Duracell but for the price i...,positive,well they are not duracell but for the price i...
3,AmazonBasics AAA Performance Alkaline Batterie...,5,Seem to work as well as name brand batteries a...,positive,seem to work as well as name brand batteries a...
4,AmazonBasics AAA Performance Alkaline Batterie...,5,These batteries are very long lasting the pric...,positive,these batteries are very long lasting the pric...

## Create Sample for Summarization
- Use a smaller sample to keep the notebook fast.

In [4]:
# use a smaller sample for fast processing
sample_df = df.sample(n=1000, random_state=42).copy()

# check sample size
sample_df.shape

(1000, 5)

## Create Embeddings and Clusters
- Use a pretrained sentence transformer and KMeans to recreate product clusters.

In [5]:
!pip install sentence-transformers -q

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans

# prepare review texts
texts = sample_df["clean_review"].tolist()

# load embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# create embeddings
embeddings = embedding_model.encode(texts, show_progress_bar=True)

# create 5 clusters
kmeans = KMeans(n_clusters=5, random_state=42)

# assign clusters
sample_df["cluster"] = kmeans.fit_predict(embeddings)

sample_df[["name", "clean_review", "cluster"]].head()

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

,name,clean_review,cluster
35736,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",this is the 2nd one we have purchased for our ...,1
24525,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",it takes forever to download apps i m returnin...,3
49321,"Echo (White),,,\r\nEcho (White),,,",excellent product tones of fun and super usabi...,1
12351,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",easy to use lots of books obviously but also l...,2
31628,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",good to have for smaller tablet use lightweigh...,3

## Inspect Clustered Sample
- Check available clusters and products in the sampled data.

In [6]:
# check sample dataset size
print(sample_df.shape)

# check available clusters
print(sample_df["cluster"].value_counts())

# inspect clustered sample
sample_df[["name", "reviews.rating", "sentiment", "cluster"]].head()

(1000, 6)
cluster
3    303
1    290
2    161
4    141
0    105
Name: count, dtype: int64

,name,reviews.rating,sentiment,cluster
35736,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5,positive,1
24525,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",1,negative,3
49321,"Echo (White),,,\r\nEcho (White),,,",5,positive,1
12351,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",5,positive,2
31628,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",4,positive,3

## Prepare Product Insights
- Extract top products, worst product, and complaints per cluster.

In [7]:
def prepare_cluster_insights(cluster_df):
    # calculate average rating per product
    product_stats = cluster_df.groupby("name").agg(
        avg_rating=("reviews.rating", "mean"),
        review_count=("reviews.rating", "count")
    ).reset_index()

    # keep products with at least 3 reviews
    product_stats = product_stats[product_stats["review_count"] >= 3]

    # top 3 products
    top_products = product_stats.sort_values(
        by="avg_rating",
        ascending=False
    ).head(3)

    # worst product
    worst_product = product_stats.sort_values(
        by="avg_rating",
        ascending=True
    ).head(1)

    # complaints (negative reviews)
    complaints = cluster_df[
        cluster_df["sentiment"] == "negative"
    ]["clean_review"].head(5).tolist()

    return top_products, worst_product, complaints

In [8]:
# test for one cluster
cluster_df = sample_df[sample_df["cluster"] == 0]

top_products, worst_product, complaints = prepare_cluster_insights(cluster_df)

print("Top products:")
print(top_products)

print("\nWorst product:")
print(worst_product)

print("\nComplaints:")
print(complaints)

Top products:
                                                name  avg_rating  review_count
4             Amazon Fire Tv,,,\r\nAmazon Fire Tv,,,    4.629630            27
9                 Echo (White),,,\r\nEcho (White),,,    4.583333            36
3  Amazon Echo Show Alexa-enabled Bluetooth Speak...    4.500000            14

Worst product:
                                          name  avg_rating  review_count
2  Amazon - Echo Plus w/ Built-In Hub - Silver         4.1            10

Complaints:
['it was a bit more involved getting set up but thereafter the function is simply talking to alexia the plug adapter to turn on and off lights tv is useful and certainly worth having', 'we returned it could not give answers to our questions even though the answers were easily found on google', 'i purchased this item on the recommendation of many existing owners however when i got home and attempted to set up the device it was frustrating and the instructions faqs were not very helpful the echo could not find my nest thermostat nor could it find about half of my hue lights once i argued and fought with alexa for about 45 minutes she finally started to pick up my lights and after comletely re configuring my thermostat she could see it but she would not work with it once she found all of my lights she would turn them on or off but would not change colors or brightness levels i run a software company and have worked in and with computers my whole life this should not have been this quirky i would not recommend this item get a google home', 'this does not give great answers and the connection is not that great exchanging for a google home', 'don t like the fact you have to have amazon prime to use it']

##Clean Product Names
- Fix formatting issues in product names.

In [15]:
# clean messy product names (remove commas, line breaks)
sample_df["name"] = sample_df["name"].str.replace(r"[\r\n,]+", " ", regex=True).str.strip()

##-----------------------------------------------------------
## Inspect Clustered Sample
- Check available clusters and products in the sampled data.

In [16]:
# check sample dataset size
print(sample_df.shape)

# check available clusters
print(sample_df["cluster"].value_counts())

# inspect clustered sample
sample_df[["name", "reviews.rating", "sentiment", "cluster"]].head()

(1000, 6)
cluster
3    303
1    290
2    161
4    141
0    105
Name: count, dtype: int64

,name,reviews.rating,sentiment,cluster
35736,Fire Tablet 7 Display Wi-Fi 8 GB - Includes...,5,positive,1
24525,Fire Kids Edition Tablet 7 Display Wi-Fi 16...,1,negative,3
49321,Echo (White) Echo (White),5,positive,1
12351,All-New Fire HD 8 Tablet 8 HD Display Wi-Fi ...,5,positive,2
31628,Fire Tablet 7 Display Wi-Fi 8 GB - Includes...,4,positive,3

##Load Generator Model
- Use a small generative model to create recommendation text.

In [17]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-1.5B-Instruct",
    max_new_tokens=300,
    device_map="auto"
)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

##Generate Recommendation Article
- Create a short blog-style summary for one cluster.

In [18]:
# select cluster
cluster_id = 0

cluster_df = sample_df[sample_df["cluster"] == cluster_id]

top_products, worst_product, complaints = prepare_cluster_insights(cluster_df)

prompt = f"""
Write a short product recommendation article.

Top products:
{top_products.to_string(index=False)}

Worst product:
{worst_product.to_string(index=False)}

Complaints:
{complaints}

Include:
- Top 3 products
- Differences
- Complaints
- Worst product warning
"""

result = generator(prompt)

print(result[0]["generated_text"])

Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Write a short product recommendation article.

Top products:
                                                           name  avg_rating  review_count
                                  Amazon Fire Tv Amazon Fire Tv    4.629630            27
                                      Echo (White) Echo (White)    4.583333            36
Amazon Echo Show Alexa-enabled Bluetooth Speaker with 7" Screen    4.500000            14

Worst product:
                                       name  avg_rating  review_count
Amazon - Echo Plus w/ Built-In Hub - Silver         4.1            10

Complaints:
['it was a bit more involved getting set up but thereafter the function is simply talking to alexia the plug adapter to turn on and off lights tv is useful and certainly worth having', 'we returned it could not give answers to our questions even though the answers were easily found on google', 'i purchased this item on the recommendation of many existing owners however when i got home and attempted to set up the device it was frustrating and the instructions faqs were not very helpful the echo could not find my nest thermostat nor could it find about half of my hue lights once i argued and fought with alexa for about 45 minutes she finally started to pick up my lights and after comletely re configuring my thermostat she could see it but she would not work with it once she found all of my lights she would turn them on or off but would not change colors or brightness levels i run a software company and have worked in and with computers my whole life this should not have been this quirky i would not recommend this item get a google home', 'this does not give great answers and the connection is not that great exchanging for a google home', 'don t like the fact you have to have amazon prime to use it']

Include:
- Top 3 products
- Differences
- Complaints
- Worst product warning
- Product recommendation
- Product recommendation note(s)
Product Recommendation:

If you're looking for an Alexa-enabled speaker, consider purchasing either the Amazon Echo Show or the Echo (White). Both are highly-rated and offer impressive features such as voice control, video calling, and smart home integration. The Amazon Echo Show offers a larger screen, making it perfect for watching videos and playing games. On the other hand, the Echo (White) is ideal if you prefer a sleek design without the extra screen. Additionally, both devices come with free Amazon Prime membership included, providing access to exclusive content and streaming services.

Note: If you've had negative experiences with the Amazon Echo Plus, be aware that setting it up can be challenging due to its complex setup process. However, once it's configured correctly, it's a fantastic addition to any smart home environment.

Product Recommendation Note:

Remember, while these devices are excellent additions to your smart home, they may require some initial setup time. Make sure to read through the user manual carefully before attempting to install them. With proper guidance and patience, you'll quickly become comfortable using these amazing voice assistants! #SmartHomeTips #AlexaSolutions #TechGadgets #HomeAutomation #DIYProjects #SmartLiving

---

**Warning:** The Amazon Echo Plus is known for being somewhat difficult to set up initially due to its complicated setup process. It requires a Google Home hub to connect properly. If you encounter issues during installation, don't hesitate to seek help

In [19]:
#Prompt Variation 2

prompt = f"""
You are a tech reviewer.

Write a short, clear product recommendation article based ONLY on the data below.

Top products:
{top_products.to_string(index=False)}

Worst product:
{worst_product.to_string(index=False)}

Customer complaints:
{complaints}

Rules:
- Be concise and factual
- Do NOT invent products
- Do NOT mention brands not listed
- Focus on differences and real issues

Structure:
1. Introduction
2. Top products comparison
3. Key complaints
4. Worst product warning
5. Final recommendation
"""

result = generator(prompt)

print(result[0]["generated_text"])

Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

You are a tech reviewer.

Write a short, clear product recommendation article based ONLY on the data below.

Top products:
                                                           name  avg_rating  review_count
                                  Amazon Fire Tv Amazon Fire Tv    4.629630            27
                                      Echo (White) Echo (White)    4.583333            36
Amazon Echo Show Alexa-enabled Bluetooth Speaker with 7" Screen    4.500000            14

Worst product:
                                       name  avg_rating  review_count
Amazon - Echo Plus w/ Built-In Hub - Silver         4.1            10

Customer complaints:
['it was a bit more involved getting set up but thereafter the function is simply talking to alexia the plug adapter to turn on and off lights tv is useful and certainly worth having', 'we returned it could not give answers to our questions even though the answers were easily found on google', 'i purchased this item on the recommendation of many existing owners however when i got home and attempted to set up the device it was frustrating and the instructions faqs were not very helpful the echo could not find my nest thermostat nor could it find about half of my hue lights once i argued and fought with alexa for about 45 minutes she finally started to pick up my lights and after comletely re configuring my thermostat she could see it but she would not work with it once she found all of my lights she would turn them on or off but would not change colors or brightness levels i run a software company and have worked in and with computers my whole life this should not have been this quirky i would not recommend this item get a google home', 'this does not give great answers and the connection is not that great exchanging for a google home', 'don t like the fact you have to have amazon prime to use it']

Rules:
- Be concise and factual
- Do NOT invent products
- Do NOT mention brands not listed
- Focus on differences and real issues

Structure:
1. Introduction
2. Top products comparison
3. Key complaints
4. Worst product warning
5. Final recommendation
6. Conclusion

The Amazon Echo Plus has become one of the most popular smart speakers available today, boasting an intuitive interface and a wide range of features including voice control, music streaming, and weather updates. However, some users have encountered difficulties setting up the device, leading to frustration and dissatisfaction.
Echo Plus is priced competitively at $100, making it a cost-effective option for those looking for a versatile smart speaker. Its ability to connect seamlessly with other devices within your home makes it particularly appealing for individuals who want to automate their daily routines.
In contrast, the Amazon Echo (White), which boasts a sleek design and high-quality sound, is favored by audiophiles and those seeking premium audio quality. The Echo's advanced noise cancellation technology ensures that you can enjoy crystal-clear sound without any distractions.
Echo (White) offers an impressive range of features such as Siri integration, ambient mode, and personalized playlists, making it a must-have for anyone looking to enhance their entertainment experience.
On the other hand, the Amazon Fire TV, while offering excellent video playback capabilities, lacks the versatility of the Echo family of devices. It primarily functions as a media center, catering to your viewing needs rather than integrating into your entire smart home ecosystem.
Echo Show stands out among the Echo lineup due to its larger screen size, which provides ample space for displaying information and navigating through various settings. While it may not offer as much functionality as the full-sized Echo, its convenience factor makes it a valuable addition to any

In [20]:
#Prompt variation 3

prompt = f"""
You are a tech reviewer.

Write a short, structured product recommendation article based ONLY on the data below.

Top products:
{top_products.to_string(index=False)}

Worst product:
{worst_product.to_string(index=False)}

Customer complaints:
{complaints}

Rules:
- Only use the information provided
- Do NOT invent features or products
- Be concise and factual

Structure:
1. Introduction
2. Top products comparison (bullet points)
3. Key complaints (bullet points)
4. Worst product warning
5. Final recommendation
"""

result = generator(prompt)

print(result[0]["generated_text"])

Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

You are a tech reviewer.

Write a short, structured product recommendation article based ONLY on the data below.

Top products:
                                                           name  avg_rating  review_count
                                  Amazon Fire Tv Amazon Fire Tv    4.629630            27
                                      Echo (White) Echo (White)    4.583333            36
Amazon Echo Show Alexa-enabled Bluetooth Speaker with 7" Screen    4.500000            14

Worst product:
                                       name  avg_rating  review_count
Amazon - Echo Plus w/ Built-In Hub - Silver         4.1            10

Customer complaints:
['it was a bit more involved getting set up but thereafter the function is simply talking to alexia the plug adapter to turn on and off lights tv is useful and certainly worth having', 'we returned it could not give answers to our questions even though the answers were easily found on google', 'i purchased this item on the recommendation of many existing owners however when i got home and attempted to set up the device it was frustrating and the instructions faqs were not very helpful the echo could not find my nest thermostat nor could it find about half of my hue lights once i argued and fought with alexa for about 45 minutes she finally started to pick up my lights and after comletely re configuring my thermostat she could see it but she would not work with it once she found all of my lights she would turn them on or off but would not change colors or brightness levels i run a software company and have worked in and with computers my whole life this should not have been this quirky i would not recommend this item get a google home', 'this does not give great answers and the connection is not that great exchanging for a google home', 'don t like the fact you have to have amazon prime to use it']

Rules:
- Only use the information provided
- Do NOT invent features or products
- Be concise and factual

Structure:
1. Introduction
2. Top products comparison (bullet points)
3. Key complaints (bullet points)
4. Worst product warning
5. Final recommendation
6. Conclusion

Product Recommendations:

1. Amazon Fire TV: It has an average rating of 4.629630 out of 5 and has received over 27 reviews. The user experience seems straightforward and practical, making it suitable for everyday usage.
2. Echo (White): With an average rating of 4.583333 out of 5, the Echo (White) offers a pleasant interaction with voice commands. However, there's a higher number of returns due to issues related to compatibility.
3. Amazon Echo Show: This smart speaker boasts an impressive 4.5 rating and 14 reviews. Its 7-inch screen makes it visually appealing and easy to navigate, perfect for users who enjoy watching videos and playing games.
4. Echo Plus w/ Built-in Hub - Silver: Despite its low rating, this model has received only 10 reviews. Users reported frustration during setup and difficulty finding specific functionality within the device.

Worst Product Warning:
The Echo Plus w/ Built-in Hub - Silver comes highly recommended by other users but can be quite disappointing. Setting it up proved challenging, and the instructions were inadequate. Once operational, the device struggled with integrating with certain devices, particularly lighting systems, causing significant inconvenience.

Final Recommendation:
While the top three products offer solid performance across various functionalities, the Echo Plus w/ Built-in Hub - Silver might not be the best choice for everyone due to its poor integration capabilities. If you

##Final Conclusions

- The project successfully demonstrates an end-to-end NLP pipeline for analyzing customer reviews.

- The sentiment classifier (DistilBERT) achieved high performance (~95% accuracy), but results are influenced by dataset imbalance, leading to weaker detection of neutral reviews.

- The clustering approach (MiniLM embeddings + KMeans) revealed meaningful product groupings, although quantitative evaluation (low silhouette score) shows that text clustering remains challenging.

- The summarization model (Qwen 1.5B) was able to generate structured recommendation articles using extracted insights such as top products and customer complaints.

- Prompt design proved to be critical for controlling output quality and reducing hallucinations in generative models.

- Overall, combining classification, clustering, and generation provides valuable business insights, transforming raw reviews into actionable recommendations.

- Limitations include dataset imbalance, noisy text data, and the inherent challenges of unsupervised clustering and generative AI reliability.