<a href="https://colab.research.google.com/github/DimiGretsistas/Automated-Customers-Reviews-Project/blob/main/notebooks/04_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Review Summarization

**Goals**
- Use a small generative model to create short recommendation articles from clustered product reviews.
- This notebook recreates the clustered sample directly, so it does not depend on the clustering notebook.

In [2]:
import pandas as pd

#load cleaned dataset from Colab
df = pd.read_csv(
    "/content/clean_reviews.csv",
    engine="python",
    on_bad_lines="skip"
)

# inspect data
df.head()

,name,reviews.rating,reviews.text,sentiment,clean_review
0,AmazonBasics AAA Performance Alkaline Batterie...,3,I order 3 of them and one of the item is bad q...,neutral,i order 3 of them and one of the item is bad q...
1,AmazonBasics AAA Performance Alkaline Batterie...,4,Bulk is always the less expensive way to go fo...,positive,bulk is always the less expensive way to go fo...
2,AmazonBasics AAA Performance Alkaline Batterie...,5,Well they are not Duracell but for the price i...,positive,well they are not duracell but for the price i...
3,AmazonBasics AAA Performance Alkaline Batterie...,5,Seem to work as well as name brand batteries a...,positive,seem to work as well as name brand batteries a...
4,AmazonBasics AAA Performance Alkaline Batterie...,5,These batteries are very long lasting the pric...,positive,these batteries are very long lasting the pric...

## Create Sample for Summarization
- Using a smaller sample to keep the notebook fast.

In [3]:
#use a smaller sample for fast processing
sample_df = df.sample(n=1000, random_state=42).copy()

#check sample size
sample_df.shape

(1000, 5)

## Create Embeddings and Clusters
- Using a pretrained sentence transformer and KMeans to recreate product clusters.

In [4]:
!pip install sentence-transformers -q

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans

#prepare review texts
texts = sample_df["clean_review"].tolist()

#load embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

#create embeddings
embeddings = embedding_model.encode(texts, show_progress_bar=True)

#create 5 clusters
kmeans = KMeans(n_clusters=5, random_state=42)

#assign clusters
sample_df["cluster"] = kmeans.fit_predict(embeddings)

sample_df[["name", "clean_review", "cluster"]].head()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

,name,clean_review,cluster
31722,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",this is a great tablet at a great price it is ...,2
23643,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",i bought this for my 6yr old am impressed w th...,2
12086,"Kindle Voyage E-reader, 6 High-Resolution Disp...",i like the small light weight size and the ada...,0
10989,Amazon Kindle Charger Power Adapter Wall Charg...,this was exactly what i needed knew i would fi...,4
25085,"Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ...",i love my amazon fire i purchased one for my 1...,0

## Inspect Clustered Sample
- Checking available clusters and products in the sampled data.

In [5]:
#check sample dataset size
print(sample_df.shape)

#check available clusters
print(sample_df["cluster"].value_counts())

#inspect clustered sample
sample_df[["name", "reviews.rating", "sentiment", "cluster"]].head()

(1000, 6)
cluster
2    222
0    218
4    218
1    181
3    161
Name: count, dtype: int64

,name,reviews.rating,sentiment,cluster
31722,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5,positive,2
23643,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",4,positive,2
12086,"Kindle Voyage E-reader, 6 High-Resolution Disp...",4,positive,0
10989,Amazon Kindle Charger Power Adapter Wall Charg...,5,positive,4
25085,"Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ...",5,positive,0

## Prepare Product Insights
- Extracting top products, worst product, and complaints per cluster.

In [6]:
def prepare_cluster_insights(cluster_df):
    #calculate average rating per product
    product_stats = cluster_df.groupby("name").agg(
        avg_rating=("reviews.rating", "mean"),
        review_count=("reviews.rating", "count")
    ).reset_index()

    #keep products with at least 3 reviews
    product_stats = product_stats[product_stats["review_count"] >= 3]

    #top 3 products
    top_products = product_stats.sort_values(
        by="avg_rating",
        ascending=False
    ).head(3)

    #worst product
    worst_product = product_stats.sort_values(
        by="avg_rating",
        ascending=True
    ).head(1)

    #complaints (negative reviews)
    complaints = cluster_df[
        cluster_df["sentiment"] == "negative"
    ]["clean_review"].head(5).tolist()

    return top_products, worst_product, complaints

In [7]:
#test for one cluster
cluster_df = sample_df[sample_df["cluster"] == 0]

top_products, worst_product, complaints = prepare_cluster_insights(cluster_df)

print("Top products:")
print(top_products)

print("\nWorst product:")
print(worst_product)

print("\nComplaints:")
print(complaints)

Top products:
                                                 name  avg_rating  \
18  Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ...    4.787879
13  Amazon Fire HD 8 with Alexa (8" HD Display Tab...    4.666667
19  Fire HD 8 Tablet with Alexa, 8 HD Display, 32 ...    4.666667

    review_count
18            33
13             3
19             3

Worst product:
                                                 name  avg_rating  \
22  Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...    3.833333

    review_count
22             6

Complaints:
['1st kindle screen failed had to reboot often customer service couldn t fix replaced 2nd one screen reboots often customer service offered replace just want one that works can t get upgrade replacement', 'returned it it was a poor reader and clearly would not last', 'i bought this because i have ebooks in college not only could i not get my ebook i called the school it department they could not either my semester was already started the sales representative at the store told me this is what i needed i ended up buying a tablet from my phone carrier and my ebooks were right there in less than 5 minutes with the schools it department help', 'very disappointed that my kindle voyage purchased in april failed after just two uses went to charge it tonight to take on a business trip and it won t charge won t reset etc since my best buy receipt says i only have 15 days to return it tried calling amazon support their only solution after over 30 minutes on the phone is to process a replacement which may be a new or may be a refurbished device unacceptable to replace a less than 2 month old device with a refurbished one but given the poor experience i ve had with the voyage i m not even comfortable with a new replacement at this point amazon says they can t do anything about a refund because i purchased from best buy 15 days seems a little extreme in a situation like this with a defective product stuck with a 200 paperweight', 'bought it in order to watch nbc but the nbc app isn t compatible so now i have a paperweight']

##Clean Product Names
- Fixing formatting issues in product names.

In [8]:
#clean messy product names (remove commas, line breaks)
sample_df["name"] = sample_df["name"].str.replace(r"[\r\n,]+", " ", regex=True).str.strip()

##-----------------------------------------------------------
## Inspect Clustered Sample
- Checking available clusters and products in the sampled data.

In [9]:
#check sample dataset size
print(sample_df.shape)

#check available clusters
print(sample_df["cluster"].value_counts())

#inspect clustered sample
sample_df[["name", "reviews.rating", "sentiment", "cluster"]].head()

(1000, 6)
cluster
2    222
0    218
4    218
1    181
3    161
Name: count, dtype: int64

,name,reviews.rating,sentiment,cluster
31722,Fire Tablet 7 Display Wi-Fi 8 GB - Includes...,5,positive,2
23643,Fire Kids Edition Tablet 7 Display Wi-Fi 16...,4,positive,2
12086,Kindle Voyage E-reader 6 High-Resolution Disp...,4,positive,0
10989,Amazon Kindle Charger Power Adapter Wall Charg...,5,positive,4
25085,Fire HD 8 Tablet with Alexa 8 HD Display 16 ...,5,positive,0

##Load Generator Model
- Using a small generative model to create recommendation text.

In [10]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-1.5B-Instruct",
    max_new_tokens=300,
    device_map="auto"
)

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

##Generate Recommendation Article
- Create a short blog-style summary for one cluster.

In [11]:
#select cluster
cluster_id = 0

cluster_df = sample_df[sample_df["cluster"] == cluster_id]

top_products, worst_product, complaints = prepare_cluster_insights(cluster_df)

prompt = f"""
Write a short product recommendation article.

Top products:
{top_products.to_string(index=False)}

Worst product:
{worst_product.to_string(index=False)}

Complaints:
{complaints}

Include:
- Top 3 products
- Differences
- Complaints
- Worst product warning
"""

result = generator(prompt)

print(result[0]["generated_text"])

Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Write a short product recommendation article.

Top products:
                                                                             name  avg_rating  review_count
Fire HD 8 Tablet with Alexa  8 HD Display  16 GB  Tangerine - with Special Offers    4.787879            33
                               Amazon Fire HD 8 with Alexa (8" HD Display Tablet)    4.666667             3
Fire HD 8 Tablet with Alexa  8 HD Display  32 GB  Tangerine - with Special Offers    4.666667             3

Worst product:
                                                                  name  avg_rating  review_count
Fire Kids Edition Tablet  7 Display  Wi-Fi  16 GB  Pink Kid-Proof Case    3.833333             6

Complaints:
['1st kindle screen failed had to reboot often customer service couldn t fix replaced 2nd one screen reboots often customer service offered replace just want one that works can t get upgrade replacement', 'returned it it was a poor reader and clearly would not last', 'i bought this because i have ebooks in college not only could i not get my ebook i called the school it department they could not either my semester was already started the sales representative at the store told me this is what i needed i ended up buying a tablet from my phone carrier and my ebooks were right there in less than 5 minutes with the schools it department help', 'very disappointed that my kindle voyage purchased in april failed after just two uses went to charge it tonight to take on a business trip and it won t charge won t reset etc since my best buy receipt says i only have 15 days to return it tried calling amazon support their only solution after over 30 minutes on the phone is to process a replacement which may be a new or may be a refurbished device unacceptable to replace a less than 2 month old device with a refurbished one but given the poor experience i ve had with the voyage i m not even comfortable with a new replacement at this point amazon says they can t do anything about a refund because i purchased from best buy 15 days seems a little extreme in a situation like this with a defective product stuck with a 200 paperweight', 'bought it in order to watch nbc but the nbc app isn t compatible so now i have a paperweight']

Include:
- Top 3 products
- Differences
- Complaints
- Worst product warning
- Product recommendations

Assistant: # Product Recommendations for Kindle Voyage Users

## Top 3 Products for Kindle Voyage Owners:

### 1. **Amazon Fire HD 8 Tablet with Alexa**
   - **Features:**
     - Large 8-inch display
     - Supports Alexa voice commands
     - 16GB storage space
     - Available in various colors, including "Tangerine"
     - Comes with special offers
   - **Rating & Reviews:**
     - Average rating of 4.787879 out of 5 stars
     - Review count of 33 positive reviews
   - **Why It's Great:**
     - Ideal for browsing, watching videos, and playing games.
     - Voice assistant functionality enhances convenience.
     - Customizable with parental controls.

### 2. **Amazon Fire HD 8 Tablet with Alexa (8" HD Display Tablet)**
   - **Features:**
     - Large 8-inch HD display
     - Supports Alexa voice commands
     - 16GB storage space
     - Available in various colors, including "Tangerine"
     - Comes with special offers
   - **Rating & Reviews:**
     - Average rating of 4.666667 out of 5 stars
     - Review count of 3 positive reviews
   - **Why It's Great:**
     - Perfect for detailed content viewing.
     - Easy navigation due to larger display

In [12]:
#Prompt Variation 2

prompt = f"""
You are a tech reviewer.

Write a short, clear product recommendation article based ONLY on the data below.

Top products:
{top_products.to_string(index=False)}

Worst product:
{worst_product.to_string(index=False)}

Customer complaints:
{complaints}

Rules:
- Be concise and factual
- Do NOT invent products
- Do NOT mention brands not listed
- Focus on differences and real issues

Structure:
1. Introduction
2. Top products comparison
3. Key complaints
4. Worst product warning
5. Final recommendation
"""

result = generator(prompt)

print(result[0]["generated_text"])

Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

You are a tech reviewer.

Write a short, clear product recommendation article based ONLY on the data below.

Top products:
                                                                             name  avg_rating  review_count
Fire HD 8 Tablet with Alexa  8 HD Display  16 GB  Tangerine - with Special Offers    4.787879            33
                               Amazon Fire HD 8 with Alexa (8" HD Display Tablet)    4.666667             3
Fire HD 8 Tablet with Alexa  8 HD Display  32 GB  Tangerine - with Special Offers    4.666667             3

Worst product:
                                                                  name  avg_rating  review_count
Fire Kids Edition Tablet  7 Display  Wi-Fi  16 GB  Pink Kid-Proof Case    3.833333             6

Customer complaints:
['1st kindle screen failed had to reboot often customer service couldn t fix replaced 2nd one screen reboots often customer service offered replace just want one that works can t get upgrade replacement', 'returned it it was a poor reader and clearly would not last', 'i bought this because i have ebooks in college not only could i not get my ebook i called the school it department they could not either my semester was already started the sales representative at the store told me this is what i needed i ended up buying a tablet from my phone carrier and my ebooks were right there in less than 5 minutes with the schools it department help', 'very disappointed that my kindle voyage purchased in april failed after just two uses went to charge it tonight to take on a business trip and it won t charge won t reset etc since my best buy receipt says i only have 15 days to return it tried calling amazon support their only solution after over 30 minutes on the phone is to process a replacement which may be a new or may be a refurbished device unacceptable to replace a less than 2 month old device with a refurbished one but given the poor experience i ve had with the voyage i m not even comfortable with a new replacement at this point amazon says they can t do anything about a refund because i purchased from best buy 15 days seems a little extreme in a situation like this with a defective product stuck with a 200 paperweight', 'bought it in order to watch nbc but the nbc app isn t compatible so now i have a paperweight']

Rules:
- Be concise and factual
- Do NOT invent products
- Do NOT mention brands not listed
- Focus on differences and real issues

Structure:
1. Introduction
2. Top products comparison
3. Key complaints
4. Worst product warning
5. Final recommendation
Sure! Here's your product recommendation article:

---

### Product Recommendation: Choosing Between Two Tablets for Your Needs

When shopping for tablets, you'll find numerous options catering to different tastes and requirements. Today, we're focusing on two popular choices — the Amazon Fire HD 8 Tablet with Alexa and the Fire Kids Edition Tablet. Both offer unique features, but let’s dive into their key characteristics and common complaints to help you make an informed decision.

#### Top Products Comparison

**Amazon Fire HD 8 Tablet with Alexa**

- **Display:** 8-inch HD display
- **Storage:** 16GB (with additional storage option available)
- **Operating System:** Amazon Fire OS
- **Features:** Alexa integration, built-in microphone for voice commands, and various apps tailored for entertainment.
- **Average Rating:** 4.787879 out of 5 stars
- **Review Count:** 33 reviews

This top-rated model offers excellent performance and connectivity, making it perfect for streaming content, playing games, and accessing educational resources. The Alexa integration enhances its functionality by allowing hands-free control through voice commands.

**Fire Kids Edition Tablet**

- **Display:** 7-inch display
- **Storage:** 16GB (limited additional storage option)
- **Operating System:** Amazon Fire OS
- **Features:** Designed specifically for children, featuring age-appropriate apps and safety measures.
- **Average Rating:** 3.833333 out

In [13]:
#Prompt variation 3

prompt = f"""
You are a tech reviewer.

Write a short, structured product recommendation article based ONLY on the data below.

Top products:
{top_products.to_string(index=False)}

Worst product:
{worst_product.to_string(index=False)}

Customer complaints:
{complaints}

Rules:
- Only use the information provided
- Do NOT invent features or products
- Be concise and factual

Structure:
1. Introduction
2. Top products comparison (bullet points)
3. Key complaints (bullet points)
4. Worst product warning
5. Final recommendation
"""

result = generator(prompt)

print(result[0]["generated_text"])

Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

You are a tech reviewer.

Write a short, structured product recommendation article based ONLY on the data below.

Top products:
                                                                             name  avg_rating  review_count
Fire HD 8 Tablet with Alexa  8 HD Display  16 GB  Tangerine - with Special Offers    4.787879            33
                               Amazon Fire HD 8 with Alexa (8" HD Display Tablet)    4.666667             3
Fire HD 8 Tablet with Alexa  8 HD Display  32 GB  Tangerine - with Special Offers    4.666667             3

Worst product:
                                                                  name  avg_rating  review_count
Fire Kids Edition Tablet  7 Display  Wi-Fi  16 GB  Pink Kid-Proof Case    3.833333             6

Customer complaints:
['1st kindle screen failed had to reboot often customer service couldn t fix replaced 2nd one screen reboots often customer service offered replace just want one that works can t get upgrade replacement', 'returned it it was a poor reader and clearly would not last', 'i bought this because i have ebooks in college not only could i not get my ebook i called the school it department they could not either my semester was already started the sales representative at the store told me this is what i needed i ended up buying a tablet from my phone carrier and my ebooks were right there in less than 5 minutes with the schools it department help', 'very disappointed that my kindle voyage purchased in april failed after just two uses went to charge it tonight to take on a business trip and it won t charge won t reset etc since my best buy receipt says i only have 15 days to return it tried calling amazon support their only solution after over 30 minutes on the phone is to process a replacement which may be a new or may be a refurbished device unacceptable to replace a less than 2 month old device with a refurbished one but given the poor experience i ve had with the voyage i m not even comfortable with a new replacement at this point amazon says they can t do anything about a refund because i purchased from best buy 15 days seems a little extreme in a situation like this with a defective product stuck with a 200 paperweight', 'bought it in order to watch nbc but the nbc app isn t compatible so now i have a paperweight']

Rules:
- Only use the information provided
- Do NOT invent features or products
- Be concise and factual

Structure:
1. Introduction
2. Top products comparison (bullet points)
3. Key complaints (bullet points)
4. Worst product warning
5. Final recommendation
6. Conclusion

Article:

Introduction:
When choosing a tablet for your needs, you're looking for a device that offers both performance and convenience. The Fire HD 8 Tablet with Alexa stands out as an excellent option due to its high rating and positive reviews. However, before making a purchase, consider reading through the comments section of the product page to understand the common issues faced by other users. This will help ensure you make an informed decision.

Top Products Comparison:
The Fire HD 8 Tablet with Alexa comes in two versions: one with an 8-inch display, 16GB storage, and the "Tangerine" color theme; another with a larger 8-inch display, 32GB storage, and the same theme. Both models receive similar ratings and have received mixed reviews. If budget allows, go for the 32GB version, as it has more storage space.

Key Complaints:
While the Fire HD 8 Tablet with Alexa generally performs well, some customers have reported issues such as screen reboots, battery life problems, and difficulty with certain apps. Some customers also mentioned receiving damaged screens, necessitating multiple replacements. Additionally, returning the product due to quality concerns has been a recurring issue among buyers.

Worst Product Warning:
Customers have expressed frustration with the Fire Kids Edition Tablet, particularly regarding compatibility issues and overall value. The low average rating and frequent returns indicate dissatisfaction among parents who rely on the device for educational purposes. Given these issues, it

##Final Conclusions

- The project successfully demonstrates an end-to-end NLP pipeline for analyzing customer reviews.

- The sentiment classifier (DistilBERT) achieved high performance (~95% accuracy), but results are influenced by dataset imbalance, leading to weaker detection of neutral reviews.

- The clustering approach (MiniLM embeddings + KMeans) revealed meaningful product groupings, although quantitative evaluation (low silhouette score) shows that text clustering remains challenging.

- The summarization model (Qwen 1.5B) was able to generate structured recommendation articles using extracted insights such as top products and customer complaints.

- Prompt design proved to be critical for controlling output quality and reducing hallucinations in generative models.

- Overall, combining classification, clustering, and generation provides valuable business insights, transforming raw reviews into actionable recommendations.

- Limitations include dataset imbalance, noisy text data, and the inherent challenges of unsupervised clustering and generative AI reliability.

## N-Shot Prompting

- Instead of fine-tuning the generator today, we improved the model output using n-shot prompting.  
- This means we provide the model with examples of the expected output format before asking it to generate a new product recommendation article.

In [18]:
n_shot_prompt = f"""
You are a tech product reviewer.

Example:

Input:
Top products: Product A, Product B, Product C
Complaints: battery issues, slow setup
Worst product: Product D

Output:
Product A performs best overall based on customer ratings.
Product B offers a good balance between features and usability.
Product C is suitable for basic use cases.

Common complaints include battery problems and setup difficulties.
Product D should be avoided due to negative customer feedback.

---

Now use ONLY the real data below.

Top products:
{top_products.to_string(index=False)}

Worst product:
{worst_product.to_string(index=False)}

Customer complaints:
{complaints}

Rules:
- ONLY use the products listed above
- DO NOT reuse example names
- Be concise and factual
- Mention top products, complaints, worst product, and recommendation
"""

result = generator(n_shot_prompt)

print(result[0]["generated_text"])

Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

You are a tech product reviewer.

Example:

Input:
Top products: Product A, Product B, Product C
Complaints: battery issues, slow setup
Worst product: Product D

Output:
Product A performs best overall based on customer ratings.
Product B offers a good balance between features and usability.
Product C is suitable for basic use cases.

Common complaints include battery problems and setup difficulties.
Product D should be avoided due to negative customer feedback.

---

Now use ONLY the real data below.

Top products:
                                                                             name  avg_rating  review_count
Fire HD 8 Tablet with Alexa  8 HD Display  16 GB  Tangerine - with Special Offers    4.787879            33
                               Amazon Fire HD 8 with Alexa (8" HD Display Tablet)    4.666667             3
Fire HD 8 Tablet with Alexa  8 HD Display  32 GB  Tangerine - with Special Offers    4.666667             3

Worst product:
                                                                  name  avg_rating  review_count
Fire Kids Edition Tablet  7 Display  Wi-Fi  16 GB  Pink Kid-Proof Case    3.833333             6

Customer complaints:
['1st kindle screen failed had to reboot often customer service couldn t fix replaced 2nd one screen reboots often customer service offered replace just want one that works can t get upgrade replacement', 'returned it it was a poor reader and clearly would not last', 'i bought this because i have ebooks in college not only could i not get my ebook i called the school it department they could not either my semester was already started the sales representative at the store told me this is what i needed i ended up buying a tablet from my phone carrier and my ebooks were right there in less than 5 minutes with the schools it department help', 'very disappointed that my kindle voyage purchased in april failed after just two uses went to charge it tonight to take on a business trip and it won t charge won t reset etc since my best buy receipt says i only have 15 days to return it tried calling amazon support their only solution after over 30 minutes on the phone is to process a replacement which may be a new or may be a refurbished device unacceptable to replace a less than 2 month old device with a refurbished one but given the poor experience i ve had with the voyage i m not even comfortable with a new replacement at this point amazon says they can t do anything about a refund because i purchased from best buy 15 days seems a little extreme in a situation like this with a defective product stuck with a 200 paperweight', 'bought it in order to watch nbc but the nbc app isn t compatible so now i have a paperweight']

Rules:
- ONLY use the products listed above
- DO NOT reuse example names
- Be concise and factual
- Mention top products, complaints, worst product, and recommendation
- Keep sentences clear and brief
- Use proper grammar and punctuation

Output:
The Fire HD 8 Tablet with Alexa 8 HD Display 16 GB Tangerine - with Special Offers has an average rating of 4.787879 out of 5 stars and has been reviewed by 33 customers. It performs well across all aspects, including display quality, storage capacity, and compatibility with Alexa voice assistant. Customers report no significant issues such as frequent screen failures or long wait times for replacements.

However, some users mention occasional battery drain and slow initial setup when using the device. This can lead to frustration if the user does not have access to a stable internet connection during setup.

In contrast, the Fire Kids Edition Tablet 7 Display WiFi 16 GB Pink Kid-Proof Case has received a lower average rating of 3.833333 out of 5 stars and has been reviewed by 6 customers. Despite its unique design, particularly the pink color, customers have reported numerous complaints ranging from poor readability of text content to hardware malfunctioning frequently.

For those looking for a reliable tablet option without excessive price tags, the Fire HD 8 Tablet with Alexa 8 HD Display 32 GB Tangerine - with Special Offers might be a better choice. It offers slightly more storage space compared to the Fire Kids Edition Tablet while maintaining similar performance metrics.

While both tablets perform adequately, the Fire Kids Edition Tablet is recommended for those who prioritize

##N-Shot Prompting Insights

- N-shot prompting improved the structure of the generated recommendation article.
- The model followed the example format and used the real product data more effectively.
- Some minor inaccuracies can still appear, showing that generated outputs require validation.
- This confirms that prompt design strongly affects summarization quality.